name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Run Flutter tests
      run: flutter test

    - name: Analyze code
      run: flutter analyze

    - name: Run linter
      run: flutter analyze lib

    - name: Build APK
      run: flutter build apk
