name: Flutter Lint

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.2'  # Replace with the desired Flutter version

      - name: Setup Flutter
        run: flutter config --no-analytics && flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter Lint
        run: flutter analyze
