name: Flutter CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run linter
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build project
        run: flutter build apk # You can change this to build other targets like web, ios, etc.
