name: Flutter CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run linter and static analysis
        run: flutter analyze

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: analyze  # Ensure analyze job completes before running this

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests with coverage
        run: flutter test --coverage

  integration_tests:
    name: Run Flutter Integration Tests
    runs-on: ubuntu-latest
    needs: test  # Ensure test job completes before running this

    services:
      xvfb:
        image: trufflesuite/ganache-cli:latest
        options: --privileged

      chromedriver:
        image: selenium/standalone-chrome
        options: --shm-size=2g
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run integration tests with Chromedriver
        run: flutter drive --target=test_driver/app.dart -d web-server
