name: Flutter CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run linter
        run: flutter analyze

  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit tests
        run: flutter test --coverage

  integration_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Start ChromeDriver server
        run: chromedriver --port=4444 --whitelisted-ips='' --url-base='' --verbose &

      - name: Wait for server to be ready
        run: sleep 10

      - name: Set FLUTTER_TEST_TIMEOUT environment variable
        run: echo "FLUTTER_TEST_TIMEOUT=120000" >> $GITHUB_ENV

      - name: Run integration tests 2
        run: flutter drive --target=test_driver/app_2.dart -d web-server --browser-name=chrome --headless --verbose

